apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend-stateful
spec:
  serviceName: "frontend-service"
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dikshat1024/frontend-app:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
  volumeClaimTemplates:
    - metadata:
        name: frontend-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi





---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  clusterIP: None   
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80